import {icons} from "./icons";

export const tabs: AppTab[] = [
    {name: "index", title: "Home", icon: icons.home},
    {name: "subscriptions", title: "Subscriptions", icon: icons.wallet},
    {name: "insights", title: "Insights", icon: icons.activity},
    {name: "settings", title: "Settings", icon: icons.setting},
];

export const HOME_USER = {
    name: "Adrian | JS Mastery",
};

export const HOME_BALANCE = {
    amount: 2489.48,
    nextRenewalDate: "2026-03-18T09:00:00.000Z",
};

export const UPCOMING_SUBSCRIPTIONS: UpcomingSubscription[] = [
    {
        id: "spotify",
        icon: icons.spotify,
        name: "Spotify",
        price: 5.99,
        currency: "USD",
        daysLeft: 2,
    },
    {
        id: "notion",
        icon: icons.notion,
        name: "Notion",
        price: 12.0,
        currency: "USD",
        daysLeft: 4,
    },
    {
        id: "figma",
        icon: icons.figma,
        name: "Figma",
        price: 15.0,
        currency: "USD",
        daysLeft: 6,
    },
];

export const ALL_SUBSCRIPTIONS: Subscription[] = [
    {
        id: "dropbox",
        icon: icons.dropbox,
        name: "Dropbox",
        plan: "Premium",
        category: "Cloud Storage",
        paymentMethod: "*****8530",
        status: "active",
        startDate: "2024-01-10T10:00:00.000Z",
        price: 16.96,
        currency: "USD",
        billing: "1 month",
        renewalDate: "2026-04-10T10:00:00.000Z",
        color: "#fff8e7",
    },
    {
        id: "spotify",
        icon: icons.spotify,
        name: "Spotify",
        plan: "Family Plan",
        category: "Entertainment",
        paymentMethod: "*****4112",
        status: "active",
        startDate: "2024-02-15T10:00:00.000Z",
        price: 76.77,
        currency: "USD",
        billing: "3 months",
        renewalDate: "2026-05-15T10:00:00.000Z",
        color: "#fff8e7",
    },
    {
        id: "github-copilot",
        icon: icons.github,
        name: "GitHub Copilot",
        plan: "Pro Business",
        category: "Developer Tools",
        paymentMethod: "*****8530",
        status: "active",
        startDate: "2024-11-24T10:00:00.000Z",
        price: 49.99,
        currency: "USD",
        billing: "1 month",
        renewalDate: "2026-03-24T10:00:00.000Z",
        color: "#fff8e7",
    },
    {
        id: "adobe",
        icon: icons.adobe,
        name: "Adobe",
        plan: "Family Plan",
        category: "Design",
        paymentMethod: "*****7784",
        status: "active",
        startDate: "2025-01-20T10:00:00.000Z",
        price: 98.10,
        currency: "USD",
        billing: "2 months",
        renewalDate: "2026-04-20T10:00:00.000Z",
        color: "#fff8e7",
    },
    {
        id: "figma",
        icon: icons.figma,
        name: "Figma",
        plan: "Premium",
        category: "Design",
        paymentMethod: "*****6631",
        status: "active",
        startDate: "2024-05-12T10:00:00.000Z",
        price: 19.23,
        currency: "USD",
        billing: "1 month",
        renewalDate: "2026-03-22T10:00:00.000Z",
        color: "#fff8e7",
    },
    {
        id: "claude-pro",
        icon: icons.claude,
        name: "Claude Pro",
        plan: "Pro Plan",
        category: "AI Tools",
        paymentMethod: "*****1010",
        status: "paused",
        startDate: "2025-06-27T10:00:00.000Z",
        price: 20.0,
        currency: "USD",
        billing: "1 month",
        renewalDate: "2026-03-27T10:00:00.000Z",
        color: "#fff8e7",
    },
    {
        id: "canva-pro",
        icon: icons.canva,
        name: "Canva Pro",
        plan: "Yearly Access",
        category: "Design",
        paymentMethod: "*****7784",
        status: "cancelled",
        startDate: "2024-04-02T10:00:00.000Z",
        price: 119.99,
        currency: "USD",
        billing: "1 year",
        renewalDate: "2026-04-02T10:00:00.000Z",
        color: "#fff8e7",
    },
    {
        id: "notion-plus",
        icon: icons.notion,
        name: "Notion Plus",
        plan: "Plus Plan",
        category: "Productivity",
        paymentMethod: "*****9021",
        status: "active",
        startDate: "2024-08-10T10:00:00.000Z",
        price: 12.0,
        currency: "USD",
        billing: "1 month",
        renewalDate: "2026-03-18T10:00:00.000Z",
        color: "#fff8e7",
    },
    {
        id: "openai-chatgpt",
        icon: icons.openai,
        name: "ChatGPT Plus",
        plan: "Plus Subscription",
        category: "AI Tools",
        paymentMethod: "*****3144",
        status: "active",
        startDate: "2024-03-01T10:00:00.000Z",
        price: 20.0,
        currency: "USD",
        billing: "1 month",
        renewalDate: "2026-03-01T10:00:00.000Z",
        color: "#fff8e7",
    },
    {
        id: "medium-membership",
        icon: icons.medium,
        name: "Medium Membership",
        plan: "Annual Member",
        category: "Reading",
        paymentMethod: "*****1120",
        status: "cancelled",
        startDate: "2023-11-05T10:00:00.000Z",
        price: 50.0,
        currency: "USD",
        billing: "1 year",
        renewalDate: "2025-11-05T10:00:00.000Z",
        color: "#fff8e7",
    },
];

export const HOME_SUBSCRIPTIONS: Subscription[] = ALL_SUBSCRIPTIONS.slice(0, 4);